#!/data/data/com.termux/files/usr/bin/bash
url="$1"; 
##
# if [ $(printf %b "$url"|grep -e "instagram") ]; then 
# cd /storage/emulated/0/Pictures; pwd; 
# yt-dlp --restrict-filenames "$url" && termux-notification --action 'termux-open $pp' -c "gg" || termux-storage-get; exit 0; fi; 
# pp="$(realpath $(ls -t /sdcard/Pictures/*.mp4|head -n1))"; 
# --paths /storage/emulated/0/Pictures; 
# termux-media-scan -r /storage/emulated/0/Pictures; 
# python $HOME/bin/igdl/igdl.py "$1" && nf="$(realpath $(command ls -t /sdcard/Pictures/igdl|head -n1))" && 
 # && termux-notification -c "$nf" --action 'termux-open $nf' && exit 0; 
## selection menu
qqmenu() { local IFS=$'\n\t ';local ops=($2);[ "$2" ]||local ops=(*);
local prompt="$1" index="0" cur="0" count="${#ops[@]}" esc=$(echo -ne "\e");
printf "\e[?25l    -- $prompt --\n\n"; ## print prompt
while true; do local index="0"; for o in "${ops[@]}"; ## print options
do if [ "$index" == "$cur" ];
then printf %b "\e[0m > \e[7m $o \e[0m\e[K\n"; ## mark & highlight the current option
else printf %b "\e[0m    $o  \e[K\n";
fi;
(( index++ ));
done; ## list all options (option list is zero-based)
read -srn1 key; ## wait for user to key in arrows or ENTER
if [[ "$key" == A ]]; then (( cur-- )); (( cur < 0 ))&& (( cur = 0 ));
elif [ "$key" == B ]; then (( cur++ )); (( cur >= count )) && (( cur = count - 1 ));
elif [[ $key == C ]]; then mark+=(${ops[$cur]});
printf %b "\e[s\e[6;22H\e[K${mark[@]}\e[K\e[u";
elif [[ $key == "" ]]; then break;
elif [[ $key == "q" ]]; then break; fi; # enter
echo -en "\e[${count}A"; done; # go up to the beginning to re-render
printf -v sel "${ops[$cur]}"; printf  "\e[?25h\n \e[7m $sel \e[0m\n\n"; }; 
####################
[ -w $HOME/sd2/Alarms ] && dir="$HOME/sd2/Alarms" || dir="$HOME/storage/downloads/"; 
####################
printf %b "$url"|bat -ppfld; printf %b "\n-\e[$((COLUMNS - 1))b\n\n"; 
####################
qqmenu "what to do?" "aria2c yt-dlp save-link-url"; 
####################
printf %b "\n whereto? 
 -- [c]hoose 
 -- [f]hoose -- f 
 -- [H]ere >> $dir\n"|bat -ppfld;  
read -srn1 "wt"; 
case $wt in 
c) dir="$(command lf -print-last-dir)";; 
f) fff; dir="$(cat $HOME/.cache/fff/.fff_d)";; 
h|*) printf %b "ok\n";; 
q) return;; esac; 
####################
case $sel in 
yt-dlp) printf %b "yt $dir / "; 
yt="$(yt-dlp --get-filename --restrict-filenames -P "$dir" "$url";)"; 
yt-dlp --restrict-filenames -P "$dir" "$url"; 
nyt="$(realpath "$yt";)"; ffmpegthumbnailer -i "$nyt" -o "$nyt.jpg"; 
termux-notification --image-path "$nyt.jpg" --action "xdg-open "$nyt"" -c "$nyt";; 
aria2c) aria2c -d "$dir" "$url";; 
save-link-url) printf %b "\n$url\n"|tee -a ${dir}/links.url;
printf %b "\n\n  saved to: \n  ${dir}/links.url\n\n  ok\n"; sleep 1;; 
# mkdir $HOME/links 2>/dev/null; 
esac; 
