#!/bin/bash
## lf config
map . set hidden! 
map <esc> quit
map i set icons!
# map F setfilterF
map <c-r> reload
map <c-q> quit
cmap <c-d> ""
cmap p "" 
map p 
cmap <c-up> "" 
map <c-up> half-up
map <a-up> half-up
map <a-down> half-down
map <c-down> half-down
map <c-d> quit
map <?> maps
map <pgdn> half-down
map <s-down> invert-below
map <pgup> half-up
# map <a-up> top
# map <a-down> bottom
map <s-up> :invert && :invert-below 
map M set mouse!
map <c-a> invert glob-select *
map a invert glob-select *
map <lt> :cd /ants
map n toch 
map <tab> :push :<tab> 
map <delete> delete
map d trash
map zu unzip
map zz zip
map c copy
map ss :search 
map sp :set preview! 
map s0 :set ratios 1
map s1 :set ratios 1:1
map s2 :set ratios 1:2
map s4 :set ratios 1:4
map s8 :set ratios 1:8
map s6 :set ratios 2:1
map s9 :set ratios 1:1:1
map s5 :set ratios 1:4:4

map sl :sese 
map sr :set reverse!
map sz :set sortby size
map sd :set drawbox!
map S :search 
map <c-s> :search-next
cmap w
map ww :search 
map 11 mark-save
map 12 :mark-load
map 122 :mark-remove 
map v paste
map k cut
map A :cd /ants
map pm :chmod_p 
map po :chown_p 
map <c-p> :reload && :history 
map 1 !true
map x $$f
map X !$f
map b !batcat -pfl d $f
cmap o 
map O $mimeopen --ask $f
map oj !jp2a --color-depth=8 --fill $f
map oc !chafa $f
map ok !cacaview $f
map ox !printf "\n\n\n\n\n\n\n\n\n\n"; exiftool $f|batcat -pl c++
map oo open $f
map or !read -rep " " -i "$fx" "x"; read -rep "to: " -i "aa@ants.ftp.sh:~/" "t"; rsync -avP "$x" "$t" ;
map op $mimeopen --ask $f
map h :cd ~
map sh :cmds
map H :maps 
map m :push %mkdir<space>
map oD :depl
map j :tajm
# map b !printf "\n\n\n\n\n\n\n\n\n\n"; exiftool $f|batcat -pl c++
map <enter> dial 
# map <enter>c !chafa $f 
map b $batcat --paging always -ld --decorations never $f 
map l :lenk
# map <enter> pger
map - maps
map _ cmds
map <+> drawbox! 
map x !$f 
map t hora
map <c-s> sese
map F :filter
map D :set dironly! 
map R :rs
map f :push F<backspace><right><backspace><right><backspace>**<left>
cmd sese ${{
mv $(basename $f) $(slugify ${f/*\/})
}}

cmd hora ${{ printf "\e[$((lf_height/2-16))H\n\n\e[2J\e[2;38;5;24m"; figlet -w $lf_width -c -fDOS_Rebel $(date +%D); printf "\e[0;1;37m"; figlet -w $lf_width -c -fDOS_Rebel $(date +%H" : "%M); printf "\e[35;5m\e[$((lf_width/2-2))G >_<\n\n\n\n\n\n\n\n\e[25m\e[0m"; read }} 
# map x :push :shell<space>$f 
# cmd tamo ${{ 
# printf "\e[2;38;5;24m"; 
# $figlet -w $lf_width -c -fDOS_Rebel $(date +%D;);
# printf "\e[0;1;37m"; 
# $figlet -w $lf_width -c -fDOS_Rebel $(date +%T;);
# printf "\e[5m\n\n"; 
# $read -n1 -rep ">_<" "aa"; 
# printf "\e[25m\e[0m\e[?47l"; 
# }}
####
####

#batcat --paging always -fpl c $f||cacaview $f||exiftool $f; read -r "x";
# map x $printf "\033[?47h\033[H\033[0J -- exif-viewer -- \n\n"; [ -x "/bin/exiftool" ]&&(exiftool $f; jp2a --width=88 --color-depth=8 $f)|batcat -pfl c --paging always; printf "\033[?47l"; 

# map x $printf "\033[?47hh \n\n\n\n\033[2A"; exiftool $f|batcat -fpl c; read -n1 -prs "" 2>/dev/null; printf "\033[?47l"; 
cmd tajm ${{ 
printf "\e[?47h\e[2J"; date +%R|figlet -w $lf_width -c -f Big_Money-nw|batcat -ppflrs; date +%^A%n%-d" "%^B|figlet -w $lf_width -c -f miniwi|batcat -ppflr; printf  "\n\n\n\n"; fortune|batcat -ppfld; printf "\n\n"; read -t60 -n1 -srp " " "aa"; [ -z "$aa" ]&& printf "\e[?47l\n\ngg\n\n"; [ -z "$aa" ]&&tajm
}} 
cmd tajm2 ${{
[ "$lf_width" ]||lf_width=${COLUMNS}; 
[ "$lf_height" ]||lf_height=${LINES}; 
printf "\e[$((lf_height/2-12))H"; 
printf "\n\e[2J\e[2;38;5;24m"; figlet -w $lf_width -c -fDOS_Rebel $(date +%A);  
printf "\n\e[2K\e[2;38;5;224m"; figlet -w $lf_width -c -fDOS_Rebel $(date +%d); 
printf "\n\e[2K\e[2;38;5;124m"; figlet -w $lf_width -c -fDOS_Rebel $(date +%B); 
printf "\n\e[2K\e[2;38;5;14m"; figlet -w $lf_width -c -fDOS_Rebel $(date +%Y); 
[ "$PREFIX" ]&& s="-s";	fortune $s|batcat -ppfl d; 
printf "\n\e[0;1;37m"; figlet -w $lf_width -c -fDOS_Rebel $(date +%H" : "%M);
printf "\e[35;5m\e[$((lf_width/2-2))G >_<\n\e[25m\e[0m"; 


}} 



cmd lenk ${{ 
read -rep "ln from: $(printf "\e[96m")" -i "$fx" "kk"; read -rep "$(printf "\e[0m")to: $(printf "\e[92m")" -i "$PWD" "kt"; printf "\e[0m"; ln "${kk}" "${kt}" --symbolic; ls $kt; sleep 1; 
}} 



####
cmd pger ${{
batcat --paging always -fpl c $f||cacaview $f||exiftool $f; read -r "x";
}}

cmd dial ${{ 
unset x a c cmds_lf; declare cmds_lf a; declare i c; 
dim="$(printf "\e[2m")"; re="$(printf "\e[0m")"; 
#for i in ${cmds_lf[*]}; do printf " $i $i \n"; done
#for i in $(seq $((lf_height/2))); do printf "\n"; done; 
cmds_lf=(
'batcat -p ' 
"ls" 
"cd" 
"chafa" 
"kakaview" 
"batcat -ppfld" 
"jp2a" 
"mediainfo"
); 
printf "\e[0m\n"; 
IFS="$(printf %b "\n")"; 
c=0; a=2; for i in ${cmds_lf[@]}; do printf " $re $((c++)) [\e[38;5;$((a++))m$dim${i:0:1}$re]$dim${i:1} \n"; done; 
printf %b "    $re["$dim"ENTER"$re"]custom\n\n\n\n\n\n\e[4A"; 
read -n1 -srep " " "x"; 
if [ "$x" != "q" ]; then 
if [ -z "$x" ]; then read -rep "Command$re: " "x"; 
printf %b "${x[*]} $f "; read -rep "[OK]? " "ok"; [ -z "$ok" ]&& ${x[*]} $f; fi; 
##
unset re dim; 
printf %b "${cmds_lf[${x}]} $f"; 
/usr/bin/${cmds_lf[${x}]} $f; 
read; 
##  case "$lf_cmd" in 
ftype="$(file -bi $f|cut -f1 -d"/")"; 
#image
#text
#audio
#inode
#application
# \e[$((lf_height/4))A
dim="$(printf "\e[2m")"; re="$(printf "\e[0m")"; 
printf "\n  --  $ftype\n"; 
# case in $ftype 
printf %b "
${dim}[${re}C${dim}]${re}hafa 
${dim}[${re}K${dim}]${re}akaview 
${dim}[${re}B${dim}]${re}atcat 
${dim}[${re}X${dim}]${re}iftool 
${dim}[${re}M${dim}]${re}ediainfo 
${dim}[${re}J${dim}]${re}p2a 
${dim}[${re}ENTER${dim}]${re}other ...${re}\n"; 
read -n1 -res "x"; 
###########
if [ -z "$x" ]; then read -rep "Command:$re " "x"; ${x[*]} $f; 
elif [ "$x" = c ]; then chafa $f; 
elif [ "$x" = k ]; then cacaview $f; 
elif [ "$x" = b ]; then batcat --paging always $f -pl d; 
elif [ "$x" = m ]; then mediainfo $f; 
elif [ "$x" = j ]; then jp2a $f --color-depth=8; 
fi; 
printf %b "\n[\e[6;92mENTER\e[0m] to return\e[A"; 
read -n1 -res; 
fi; 
}}
#set drawbox
# set '-eu' options for shell commands These options are used to have safer shell commands. Option '-e' is used to exit on error and option '-u' is used to give error for unset variables. Option '-f' disables pathname expansion which can be useful when $f, $fs, and $fx variables contain names with '*' or '?' characters. However, this option is used selectively within individual commands as it can be limiting at times.
# exiftool $f|batcat --paging always -pl c++; read; 
set shellopts '-eu'
set ifs ""
set scrolloff 20
set cursorpreviewfmt "\033[7;2m"
## cmds
cmd open &{{
case $(file --mime-type -Lb $f) in
text/*) lf -remote "send $id \$$EDITOR \$f";;
*) for f in $f; do $OPENER $f > /dev/null 2> /dev/null & done;;
esac
}}
cmd depl ${{
bash -c 'read -n1 -rp "this you? ${PWD##*/} " "gg"; [ "$gg" ]||npx wrangler pages deploy ./ --project-name ${PWD##*/} --commit-dirty=true; echo gg; '
}}
cmd toch ${{
seq 12; printf "\e[12A\e[J"; pwd; lsd -p 2>/dev/null|tail -c44; 
read -rp " -- newfile: " -i "$" "nf"; touch "$nf"; 
read -rp " -- edit $(realpath $nf) $nf [Y/n] " "yn"; [ $yn ]||$EDITOR $nf
}}



cmd trash ${{
set -f
printf "\n--------\n\n\n\n$fx\n--------\n\n"
printf "delete? [T]rash [P]ermanent [A]bort "
read -n1 -rp " " "ans";
if [ "$ans" = "t" ]; then
mkdir -p ~/.trash 2>/dev/null;
mv $fx ~/.trash/;
elif [ "$ans" = "d" ]; then
rm -rf $fx;
elif [ "$ans" = "p" ]; then
printf "delete? [Y/n]"
read -n1 -rp " " "ans"; 
if [ "$ans" != "n" ]; then 
rm -rf $fx; else echo ok; fi; 
fi; 
}}
cmd delete ${{
set -f; printf "\n\n\n\n$fx\n"; printf "delete? [Y/n]"; read -n1 -rp " " "ans"; 
if [ -z "$ans" ]; then rm -rf $fx; elif [ "$ans" = y ]; then rm -rf $fx; fi; 
}}

# use '<delete>' key for either 'trash' or 'delete' command
# map <delete> trash
# map <delete> delete

# extract the current file with the right command
# (xkcd link: https://xkcd.com/1168/)
cmd unzip ${{
mkdir $f_f; cp $f $f_f; cd $f; 
    set -f
    case $f in
        *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
        *.tar.gz|*.tgz) tar xzvf $f;;
        *.tar.xz|*.txz) tar xJvf $f;;
        *.zip) unzip $f;;
        *.rar) unrar x $f;;
        *.7z) 7z x $f;;
    esac
}}

# compress current file or selected files with tar and gunzip
cmd tar ${{
    set -f
    mkdir $1
    cp -r $fx $1
    tar czf $1.tar.gz $1
    rm -rf $1
}}

# cmd zip ${{
# set -f
# cp -r $fx $f
# mkdir $f
# zip -r $f.zip $f
# # rm -rf $1
# }}
# # 
#  cmd zip ${{
#  set -f
# zip -r $f.zip $fx
#  }} 


 
cmd zip ${{
printf "\n\n\n\nfiles: 
--
$fx
--
";
set -f; 
read -rp " ~ zip-name: " "ee";
zip -r $ee.zip $fx
}}

# compress current file or selected files with zip
#zip ${{
#zip $1.zip $1
#}}

cmd chmod_p ${{
printf "\n\n\e[36m$fx\e[0m\n----\nchmod:"; 
read -rep " " -i "775" "chmod"; 
chmod $chmod $fx||sudo chmod $chmod $fx; 
lf -remote "send $id unselect *"; 
lf -remote "send $id reload"; 
}}

cmd chown_p ${{
printf "\n\n\e[36m$fx\e[0m\n----\nchmod:"; 
read -rep " " -i "$LOGNAME" "chown"; 
chown $chown $fx||sudo chown $chown $fx; 
lf -remote "send $id unselect *"; 
lf -remote "send $id reload"; 
}}



cmd rs ${{
# for i in $(seq $lf_height); do printf "\n"; done; 
# printf "\e[A\e[2K\n\n\e[12A"
printf "\e[?47h\e[H\e[0J\n\ngg\n\n"
rs=($fx); 
printf "\e[7m rsync files: \e[0m\n"; 
printf "\e[32m${rs[*]}\n\n\n\n\e[0m\e[7m rsync reciever: \e[0m\n"; 
rsto="$(ls $ants/sh/config/ssh|fzf --margin 0,12,0,12 --border rounded --preview 'cat $ants/sh/config/ssh/{}' --preview-window border-left  --info=inline --height='~22%' --scroll-off=12 --header '-- ssh to: --')"; 
# rs=("$(ls -ptr|grep -v '/'|fzf --height='~42%' --scroll-off=12 -m --info=inline --margin 0,12,0,12 --border rounded --preview 'cat {}' --preview-window border-left)"); 
printf "\e[A\e[2K\n -- to: \t"; 
[ "${rsto}" = "new" ] && read -rep " " -i "192.168.0.10" 'rsto'; 
read -rep " " -i "$rsto" 'rsto'; 
printf " -- user: \t"; 
read -rep " " -i 'aa' 'rsuser'; 
printf " -- folder: \t"; 
read -rep " " -i '~/rs/' 'rsfold'; 
printf "\n"; 
rsync -a --info=name1 ${rs[*]} ${rsuser}@${rsto}:${rsfold} ; 
printf "\n\e[7m$rsuser@$rsto:$rsfold\e[0m\n";
ssh "$rsuser"@"$rsto" 'printf "\n\e[35m$HOME'"${rsfold/\~/}"'\n\n\e[0m"; ls -ptcr '"$rsfold"'|tail -n12';
lf -remote "send $id unselect *"; 
lf -remote "send $id reload"; 
read; printf "\e[?47l\n"
}}



#fzf --margin 0,12,0,12 --height ~12% --preview "cat {}" --border rounded
# 
# cmd rs ${{
# printf "\n\n\e[36m$fx\e[0m\n----\nchmod:"; 
# read -rep " " -i "775" "chmod"; 
# sudo chmod $chmod $fx; 
# lf -remote "send $id unselect *"; 
# lf -remote "send $id reload"; 
# }}

# 
# cmd tata ${{
# printf " tt\tll";
# read -rep " " -i "aa $id aaaal" "chmod";
# $(lf -remote "send $id echomsg "$id qqqq"");
# }}
# Main options
# set icons
# set sixel true
# set period 1
#set relativenumber
#set number
#set hiddenfiles "*.aux:*.log:*.bbl:*.bcf:*.blg:*.run.xml"
set hiddenfiles ".*"
set cleaner "~/.config/lf/cleaner"
set previewer "~/.config/lf/previewer"
set incsearch true
set incfilter true
set globsearch true
set ratios 1:1 
#2:2:6 # 2:3:7:7
#set truncatechar "..."
# set waitmsg ">_<"
set dircounts

set errorfmt 		"\033[7;31m"
set tabstop 2
set scrolloff 22
set wrapscroll
set borderfmt "\033[38;5;200m"
# set rulerfmt "%df:acc:progress:selection:filter:ind"
#set rulerfmt "\033[38;5;200m|| %s \033[0m|\033[2;32m%{lf_user_selected_size}\033[0m 
#\033[2m| %i \033[0;1;98m\e/\033[2m %t |
#\033[0m \033[0m %d \033[0m "
#set timefmt "\033[36m2006\033[0m-\033[95mJan\033[0m-\033[31m02\033[94m\033[0m-\033[92m15:04:05\033[0m" 
set timefmt 'Mon Jan _2 15:04:05 2006' ## default
set infotimefmtnew "Jan-02-15:04"
set infotimefmtold "Jan+02+15:04" 

set promptfmt "
\033[37m\033[48;2;15;25;25m  %w/
\033[96m   
\033[48;2;35;38;39;38m  %u\033[97m@\033[38;2;235;138;139;38m%h
\033[96m\033[48;2;38;84;86m\033[0m%f
\033[0m"
##
set statfmt "\033[36m%p\033[0m| %c| %u| %g| %S| %t| -> %l" ## default
set rulerfmt "%a  |%p  |\033[7;31m %m \033[0m| %{lf_user_selected_size} |\033[7;33m %c \033[0m  |\033[7;35m %s \033[0m  |\033[7;34m %f \033[0m  |%i/%t " 
cmd on-select &{{ s=$(find $fx -type f -maxdepth 1 -ls | awk '{total += $7} END {print total}' | numfmt --to=iec --format='%.2fB')
lf -remote "send $id set user_selected_size $s" }} 
##
set cursorparentfmt "\033[44m" 
set cursorpreviewfmt "\033[4m" 
set cursoractivefmt "\033[7m" 
set drawbox false
set mouse
set icons
set shell bash
set info size:time
set sortby time
set reverse 
%test $LF_LEVEL -eq 1 || >&2 printf "Warning: You're in a nested lf instance!"
source "~/.config/lf/opener"
# source "~/.config/lf/lf_m"










