#!/bin/sh


#unbind C-Space
#set -g prefix2 C-Space
# bind C-Space send-prefix
set -g prefix C-a 
bind C-a send-prefix \; display "AAAA!"
bind r source-file ~/.tmux.conf \; display "Reloaded!" # quick reload
set -g mouse on
set -g default-terminal 'screen-256color'
bind-key m set-option -g mouse \; display "Mouse: #{?mouse,ON,OFF}"

# bind m set mouse on \; display "mouse on __ (M) to off!"
# bind M set mouse off \; display "mouse off __ (M) to on!"
bind c copy-mode
bind Enter copy-mode
bind -T copy-mode k send-keys -X copy-selection
bind b choose-buffer
bind p paste-buffer
bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fh -c "#{pane_current_path}"
#Disable exit-empty
set -s exit-empty off

# Change pane colors
set -g pane-active-border fg=cyan 
set -ag pane-active-border bg=0
# Use xclip to copy and paste with the system clipboard
bind C-c run "tmux save-buffer - | tee -a ~/logs/tmuxclip.log"
bind C-v run "tmux set-buffer $(head -n ~/logs/tmuxclip.log); tmux paste-buffer"



#{?#{N/s:_popup_#S},+, }#S

set -g status-left-length 100
set -g status-right-length 100
set -g status-style bg=default
set -g status-left-style fg=6,bg=0
set -g status-right-style fg=colour0,bg=colour7
set -g status-left '#(cat ~/logs/iploc.log) #[nobold]'
# set -g status-right-style fg=colour250
set -g status-right '#[reverse]#(cat ~/logs/bp.log) #[noreverse] %A %d %B #[reverse] %H:%M'

# WINDOW INDICATORS
set -g window-status-separator ''
set -g window-status-format ' #P#{?#{window_zoomed_flag},+, }│ #P '
set -g window-status-style fg=colour245,bg=default
set -g window-status-activity-style fg=colour4,bg=default,bold
set -g window-status-bell-style fg=colour0,bg=colour9,bold
set -g window-status-current-format ' #P#{?#{window_zoomed_flag},+, }#[reverse] #W '
set -g window-status-current-style fg=colour231,bg=colour240,bold

