#!/bin/sh
#unbind C-Space
#set -g prefix2 C-Space
# bind C-Space send-prefix
set -g prefix C-a 
bind C-a send-prefix 
bind r source-file $HOME/.tmux.conf \; run ". ~/start/config/tmux/tmuxbg.sh"
#'tmux set-option -g status-style bg="$((RANDOM%6))"'
# quick reload
set -g mouse on
set -g default-terminal 'xterm-256color'
bind-key m set-option -g mouse
# \; display "Mouse: #{?mouse,ON,OFF}"
set set-clipboard on
# bind m set mouse on \; display "mouse on __ (M) to off!"
# bind M set mouse off \; display "mouse off __ (M) to on!"
bind c copy-mode
bind Enter copy-mode 
# send-keys -X cursor-up
# bind -T copy-mode x display-message "$$(tail -n1 ~/logs/tm.log)"
bind -T copy-mode Enter send-keys -X copy-selection \;  

#save-buffer ~/logs/tm.log
bind -T copy-mode k send-keys -X copy-selection \;  

#save-buffer \; run ~/logs/buffer.log \; send q
bind -T copy-mode c send-keys -X copy-selection \;
# save-buffer ~/logs/buffer.log
bind -T copy-mode Space send-keys -X begin-selection 
bind b choose-buffer
bind S command-prompt "new-window -n %1 'ssh %1'"
bind p paste-buffer
bind-key C set-option -g status-style bg=$((RANDOM%7))
bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fh -c "#{pane_current_path}"
bind-key '|' split-window -fh -c "#{pane_current_path}"
#Disable exit-empty
set -s exit-empty off
bind u run -c "tmux capture-pane -J -p|grep -oE '(https?):\/\/.*[^>]'|fzf"
# xdg-open $url
 # || termux-open-url $url ; 
# Change pane colors
# --bind alt-a:select-all,alt-d:deselect-all; 
set -g pane-active-border fg=cyan 
set -ag pane-active-border bg=0
# Use xclip to copy and paste with the system clipboard

bind C-c run "tmux save-buffer ~/logs/tmuxclip.log"
bind C-v run "tmux set-buffer $(head -n ~/logs/tmuxclip.log); tmux paste-buffer"
set -g set-titles on
set -g focus-events on
le="$SSH_CONNECTION"
# le={ps}
tmux_conf_copy_to_os_clipboard=true
tmux_conf_urlscan_options="--compact --dedupe"
#{?#{N/s:_popup_#S},+, }#S

set -g status-left-length 100
set -g status-right-length 100
# set -g status-style bg=$((RANDOM%7))
set -g status-left-style fg=7,bg=0
set -g status-right-style fg=0,bg=7
# ssh=$(ps\ a|grep\ -m1\ -e\ "ssh"|tr\ -s\ ' '\ "\n"|tail\ -n1)
ssh=$SSH_CONNECTION
# set -g message-line 4
# terminal-features ccolour 
set -g status-left '#{USER}#{hostname_full_ssh}#[bg=colour204]#(tail -c 12 ~/logs/iploc.log)'
#{SSH}#{$username}#{SSH_CONNECTION}#{DISPLAY}#{username_ssh}#{hostname_full_ssh}#[nobold]

# set -g status-centre-style fg=colour25
# set -g status-centre '#I'

# set -g status-right '#{P:#{?pane_active,#[reverse],}#{pane_index}[#{pane_width}x#{pane_height}]#[default]}#{?mouse,#[bg=red]µ#[default],}#[default]#[default]#[noreverse]%A %d %B#[reverse]%H:%M'
# WINDOW INDICATORS
# set -g status-separator '|'
set -g window-status-separator '!'
set -g window-status-format ' #P#{?#{window_zoomed_flag},-, }│ #P %U '
set -g window-status-style fg=colour245,bg=default
set -g window-status-activity-style fg=colour4,bg=default,bold
set -g window-status-bell-style fg=colour0,bg=colour9,bold
set -g window-status-current-format '#{ssh_user}#{}#{?#{window_zoomed_flag},+,}#[reverse]#W'
set -g window-status-current-style fg=colour231,bg=colour240,bold
set -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'
# set -g @plugin 'tmux-plugins/tmux-sidebar'

set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
run '~/.tmux/plugins/tpm/tpm'
