#!/bin/bash
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix
set-option -g status on
# set-option -g status-style bg=ff44
set-option -g status-style fg=18
# set-option -g default-command "exec /bin/ksh"
# set-option -g lock-after-time 1800
bind b set-option status
bind - split-window -v
bind _ split-window -h
# bind-key S command-prompt "new-window -n %1 ssh %1"
bind r source-file ~/.tmux.conf \; display "Reloaded!"
